#SET OPERATIONS
x=set("Welcome to Python World")
print(x)

#DEFINE SET DATA TYPE
l = ['s','s','d']

#CONVERT LIST TO SET
g = set(l)

'''
PRINT A SET ( IT REMOVES A DUPLICATE CHARACTERS FROM A LIST
SET IS AN UNORDERED COLLECTION WHICH HAS UNIQUE ELEMENT IN IT
'''
#PRINT SET
print(g)

#PRINT LENGTH
print(len(g))